"""Bash alias database service."""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from A.data.base import SQLiteDB


# Legacy autish paths
_AUTISH_CONFIG_DIR = Path.home() / ".config" / "autish"
_AUTISH_ALIASES_DB = _AUTISH_CONFIG_DIR / "bash_aliases.db"
_AUTISH_ALIASES_FILE = Path.home() / ".autish_aliases"

# A-specific path
_A_BASH_ALIASES = Path.home() / ".A_bash_alias"


@dataclass
class BashAlias:
    uid: int
    alias: str
    function: str
    notes: Optional[str]
    created_at: Optional[datetime]
    updated_at: Optional[datetime]


# Schema for the aliases table
SCHEMA = {
    "aliases": """
        CREATE TABLE IF NOT EXISTS aliases (
            uid INTEGER PRIMARY KEY,
            alias TEXT UNIQUE NOT NULL,
            function TEXT NOT NULL,
            notes TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT
        )
    """,
    "idx_alias": "CREATE INDEX IF NOT EXISTS idx_alias ON aliases(alias)",
    "idx_created_at": "CREATE INDEX IF NOT EXISTS idx_created_at ON aliases(created_at)",
}


class BashAliasDB:
    """Bash alias database using A.data.base.SQLiteDB."""

    def __init__(self, db_path: Path):
        self.db_path = db_path
        # Ensure parent directory exists
        db_path.parent.mkdir(parents=True, exist_ok=True)
        # Use A's SQLiteDB with schema
        self._db = SQLiteDB(db_path, SCHEMA)

    def _row_to_alias(self, row: dict) -> BashAlias:
        """Convert database row to BashAlias dataclass."""
        return BashAlias(
            uid=row["uid"],
            alias=row["alias"],
            function=row["function"],
            notes=row["notes"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )

    def add_alias(self, alias: str, function: str, notes: Optional[str] = None) -> int:
        """Add a new bash alias."""
        now = datetime.now().isoformat()
        with self._db.transaction() as conn:
            cursor = conn.execute(
                "INSERT INTO aliases (alias, function, notes, created_at) VALUES (?, ?, ?, ?)",
                (alias, function, notes, now),
            )
            return cursor.lastrowid

    def get_alias(self, uid: int) -> Optional[BashAlias]:
        """Get alias by uid."""
        row = self._db.execute_one(
            "SELECT uid, alias, function, notes, created_at, updated_at FROM aliases WHERE uid = ?",
            (uid,),
        )
        return self._row_to_alias(row) if row else None

    def list_aliases(self, sort_by: str = "created_at", descending: bool = True) -> list[BashAlias]:
        """List all aliases."""
        # Validate sort_by to prevent injection
        valid_sort = {"alias", "created_at", "updated_at"}
        if sort_by not in valid_sort:
            sort_by = "created_at"
        order = "DESC" if descending else "ASC"
        rows = self._db.execute(
            f"SELECT uid, alias, function, notes, created_at, updated_at FROM aliases ORDER BY {sort_by} {order}"
        )
        return [self._row_to_alias(r) for r in rows]

    def update_alias(
        self, uid: int, alias: Optional[str] = None, function: Optional[str] = None, notes: Optional[str] = None
    ) -> bool:
        """Update an existing alias."""
        updates = []
        values = []
        if alias:
            updates.append("alias = ?")
            values.append(alias)
        if function:
            updates.append("function = ?")
            values.append(function)
        if notes is not None:
            updates.append("notes = ?")
            values.append(notes)
        if updates:
            updates.append("updated_at = ?")
            values.append(datetime.now().isoformat())
            values.append(uid)
            with self._db.transaction() as conn:
                conn.execute(f"UPDATE aliases SET {', '.join(updates)} WHERE uid = ?", tuple(values))
            return True
        return False

    def delete_alias(self, uid: int) -> bool:
        """Delete an alias by uid."""
        with self._db.transaction() as conn:
            conn.execute("DELETE FROM aliases WHERE uid = ?", (uid,))
        return True

    def search_aliases(self, query: str) -> list[BashAlias]:
        """Search aliases by alias, function, or notes."""
        rows = self._db.execute(
            "SELECT uid, alias, function, notes, created_at, updated_at FROM aliases "
            "WHERE alias LIKE ? OR function LIKE ? OR notes LIKE ?",
            (f"%{query}%", f"%{query}%", f"%{query}%"),
        )
        return [self._row_to_alias(r) for r in rows]

    def sync_shell_config(self) -> None:
        """Sync aliases to shell config (generated, read-only)."""
        aliases = self.list_aliases()
        output = ["#!/bin/bash", "# Auto-generated by A", ""]
        for a in aliases:
            output.append(f'alias {a.alias}="{a.function}"')
        
        config = Path.home() / ".A_bash_alias"
        if config.exists():
            config.chmod(0o644)  # Make writable before overwriting
        config.write_text("\n".join(output) + "\n")
        config.chmod(0o444)  # Read-only to prevent user edits

    def close(self) -> None:
        """Close database connection (no-op for SQLiteDB)."""
        pass


# Autish → A command mapping for rewriting alias function bodies
_AUTISH_TO_A: dict[str, str] = {
    "autish": "A",
    "encik": "A encik",
    "vorto": "A vorto",
    "kalendaro": "A kalendaro",
    "tempo": "A tempo",
    "sistemo": "A sistemo",
    "retposto": "A lien retposto",
    "kontakto": "A lien kontakto",
    "todo": "A todo",
    "taglibro": "A taglibro",
}


def _has_autish_command(body: str) -> bool:
    """Check if an alias function body contains autish-legacy commands.
    
    Args:
        body: Alias function string
        
    Returns:
        True if any autish command is referenced
    """
    import re
    for autish_cmd in _AUTISH_TO_A:
        if re.search(rf'(^|[|;])\s*{autish_cmd}\b', body):
            return True
    return False


def _rewrite_autish_function(body: str) -> str:
    """Rewrite autish commands embedded in an alias function body.

    E.g. 'encik serci "query"' → 'A encik serci "query"'

    Args:
        body: Alias function string

    Returns:
        Rewritten function string
    """
    import re
    for autish_cmd, a_cmd in _AUTISH_TO_A.items():
        body = re.sub(
            rf'(^|[|;])(\s*){autish_cmd}\b',
            rf'\1\2{a_cmd}',
            body,
        )
    return body


def migrate_from_autish(target_db: BashAliasDB) -> dict:
    """Migrate bash aliases from autish-legacy to A-sistemo.
    
    Args:
        target_db: Target BashAliasDB to migrate into
        
    Returns:
        Dict with migration results
    """
    results = {
        "source": 0,
        "migrated": 0,
        "skipped": 0,
        "errors": [],
    }
    
    # Check if legacy DB exists
    if not _AUTISH_ALIASES_DB.exists():
        return results
    
    try:
        legacy = sqlite3.connect(str(_AUTISH_ALIASES_DB))
        legacy.row_factory = sqlite3.Row
    except Exception as e:
        results["errors"].append(f"Could not connect to legacy DB: {e}")
        return results
    
    # Get existing aliases for idempotency
    existing_map = {a.alias: a for a in target_db.list_aliases()}
    rows = legacy.execute("SELECT * FROM bash_aliases").fetchall()
    results["source"] = len(rows)
    
    for row in rows:
        alias_name = row["alias"]
        old_function = row["function"]
        new_function = _rewrite_autish_function(old_function)
        changed = new_function != old_function
        
        if alias_name in existing_map:
            existing_alias = existing_map[alias_name]
            # Update if function body changed (autish → A rewrite)
            if changed:
                target_db.update_alias(
                    uid=existing_alias.uid,
                    funkcio=new_function,
                )
                results["migrated"] += 1
            else:
                results["skipped"] += 1
            continue
        
        try:
            notes_val = row["notes"] if row["notes"] else None
            target_db.add_alias(
                alias=alias_name,
                function=new_function,
                notes=notes_val,
            )
            results["migrated"] += 1
        except Exception as e:
            results["errors"].append(f"{alias_name}: {e}")
    
    legacy.close()
    
    return results


def migrate_bashrc(target_db: BashAliasDB) -> dict:
    """Update ~/.bashrc to source A aliases instead of autish.
    
    Returns:
        Dict with results
    """
    results = {
        "removed_autish": False,
        "added_A": False,
        "error": None,
    }
    
    bashrc = Path.home() / ".bashrc"
    if not bashrc.exists():
        return results
    
    content = bashrc.read_text()
    lines = content.split("\n")
    
    new_lines = []
    autish_source_found = False
    A_source_found = False
    
    for line in lines:
        # Remove autish source line only
        if "autish_aliases" in line and "source" in line.lower():
            autish_source_found = True
            continue
        # Skip if already have A source
        if ".A_bash_alias" in line:
            A_source_found = True
            continue
        new_lines.append(line)
    
    # Add A source line if not present
    if not A_source_found:
        new_lines.append("")
        new_lines.append("# A bash aliases")
        new_lines.append("source ~/.A_bash_alias")
        results["added_A"] = True
    
    # Write updated bashrc
    try:
        bashrc.write_text("\n".join(new_lines) + "\n")
        results["removed_autish"] = autish_source_found
    except Exception as e:
        results["error"] = str(e)
    
    return results


__all__ = ["BashAlias", "BashAliasDB", "migrate_from_autish", "migrate_bashrc"]